packages:
  - 'apps/*'
  - 'libs/*'
allowBuilds:
  '@nestjs/core': set this to true or false
  bcrypt: set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  nice-napi: set this to true or false
  sqlite3: set this to true or false
