# Generated by Django 3.1.7 on 2021-04-26 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=150, verbose_name='House name')),
                ('meter', models.IntegerField(default=1)),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseTenantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_tenant', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.IntegerField(default=0)),
                ('house_name_FK', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='house_tenant_related', to='share.housenamemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HouseBillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bill', models.FloatField()),
                ('start_date_bill', models.DateField()),
                ('end_date_bill', models.DateField()),
                ('days_bill', models.IntegerField(default=0)),
                ('house_bill_FK', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='house_bill_related', to='share.housenamemodel')),
            ],
        ),
    ]
