# Generated by Django 3.1.7 on 2021-12-28 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(blank=True, max_length=100, null=True)),
                ('meter', models.IntegerField(default=1)),
                ('last_updated_house', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main House Name',
                'verbose_name_plural': 'Main House Names',
                'ordering': ['-last_updated_house'],
            },
        ),
        migrations.CreateModel(
            name='SubHouseNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_house_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub House Name')),
                ('sub_meter', models.IntegerField(blank=True, default=1, null=True)),
                ('sub_main_house', models.BooleanField(help_text='Is the bill belongs this house typed above?')),
                ('sub_last_updated_house', models.DateTimeField(auto_now_add=True, null=True)),
                ('sub_house_FK', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_house_related', to='share.housenamemodel')),
            ],
            options={
                'verbose_name': 'Sub House Name',
                'verbose_name_plural': 'Sub House Names',
                'ordering': ['-sub_last_updated_house'],
            },
        ),
        migrations.CreateModel(
            name='SubTenantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_house_tenant', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_start_date', models.DateField(blank=True, null=True)),
                ('sub_end_date', models.DateField(blank=True, null=True)),
                ('sub_days', models.IntegerField(blank=True, default=0, null=True)),
                ('sub_last_updated_tenant', models.DateTimeField(auto_now=True, null=True)),
                ('main_tenant_FK', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_house_tenant_related', to='share.housenamemodel')),
                ('sub_house_tenant_FK', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_house_tenant_related', to='share.subhousenamemodel')),
            ],
            options={
                'verbose_name': 'Sub House Tenant',
                'verbose_name_plural': 'Sub House Tenants',
                'ordering': ['-sub_last_updated_tenant'],
            },
        ),
        migrations.CreateModel(
            name='SubKilowattModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sub_amount_bill', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sub_last_read_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sub_read_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sub_last_updated_kwh', models.DateTimeField(auto_now=True, null=True)),
                ('main_house_kwh_FK', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_house_kilowatt_related', to='share.housenamemodel')),
                ('sub_house_kwh_FK', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_house_kilowatt_related', to='share.subhousenamemodel')),
            ],
            options={
                'verbose_name': 'Sub House Kilowatt',
                'verbose_name_plural': 'Sub House Kilowatts',
                'ordering': ['-sub_last_updated_kwh'],
            },
        ),
        migrations.CreateModel(
            name='HouseTenantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_tenant', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.IntegerField(blank=True, default=0, null=True)),
                ('last_updated_tenant', models.DateField(auto_now=True, null=True)),
                ('house_name_FK', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_tenant_related', to='share.housenamemodel')),
            ],
            options={
                'verbose_name': 'Main House Tenant',
                'verbose_name_plural': 'Main House Tenants',
                'ordering': ['-last_updated_tenant'],
            },
        ),
        migrations.CreateModel(
            name='HouseKilowattModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('last_read_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('read_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('last_updated_kwh', models.DateTimeField(auto_now=True, null=True)),
                ('house_kwh_FK', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_kilowatt_related', to='share.housenamemodel')),
            ],
            options={
                'verbose_name': 'Main House Killowatt',
                'verbose_name_plural': 'Main House Killowatts',
                'ordering': ['-last_updated_kwh'],
            },
        ),
        migrations.CreateModel(
            name='HouseBillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bill', models.CharField(blank=True, max_length=22, null=True)),
                ('start_date_bill', models.DateField()),
                ('end_date_bill', models.DateField()),
                ('days_bill', models.IntegerField(default=0)),
                ('last_updated_bill', models.DateTimeField(auto_now=True, null=True)),
                ('house_bill_FK', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_bill_related', to='share.housenamemodel')),
            ],
            options={
                'verbose_name': 'Main House Bill',
                'verbose_name_plural': 'Main House Bills',
                'ordering': ['-last_updated_bill'],
            },
        ),
    ]
