# Generated by Django 3.1.7 on 2021-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20210430_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebillmodel',
            name='amount_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
