# Generated by Django 3.1.7 on 2021-05-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20210430_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebillmodel',
            name='amount_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='HouseKilowattModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh', models.IntegerField(blank=True, null=True)),
                ('last_read_kwh', models.IntegerField(blank=True, null=True)),
                ('read_kwh', models.IntegerField(blank=True, null=True)),
                ('last_updated_kwh', models.DateField(auto_now_add=True, null=True)),
                ('house_kwh_FK', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='house_kilowatt_related', to='share.housenamemodel')),
            ],
            options={
                'ordering': ['-last_updated_kwh'],
            },
        ),
    ]
