# Generated by Django 3.1.7 on 2021-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20210504_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebillmodel',
            name='last_updated_bill',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='kwh',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='KWH'),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='last_updated_kwh',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='housenamemodel',
            name='house_name',
            field=models.CharField(max_length=150, verbose_name='House Name'),
        ),
        migrations.AlterField(
            model_name='housetenantmodel',
            name='last_updated_tenant',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
