# Generated by Django 3.1.7 on 2021-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_auto_20210504_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='housenamemodel',
            name='kwh',
            field=models.IntegerField(blank=True, null=True, verbose_name='KWH'),
        ),
        migrations.AddField(
            model_name='housenamemodel',
            name='last_read_kwh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housenamemodel',
            name='last_updated_kwh',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='housenamemodel',
            name='read_kwh',
            field=models.IntegerField(blank=True, help_text='Should be greatter than last read Kwh', null=True),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='kwh',
            field=models.IntegerField(blank=True, null=True, verbose_name='KWH'),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='read_kwh',
            field=models.IntegerField(blank=True, help_text='Should be greatter than last read Kwh', null=True),
        ),
    ]
