# Generated by Django 3.1.7 on 2021-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_auto_20210510_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='housenamemodel',
            name='main_house',
            field=models.BooleanField(default=False),
        ),
    ]
