# Generated by Django 3.1.7 on 2021-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_housenamemodel_main_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housenamemodel',
            name='kwh',
        ),
        migrations.RemoveField(
            model_name='housenamemodel',
            name='last_read_kwh',
        ),
        migrations.RemoveField(
            model_name='housenamemodel',
            name='last_updated_kwh',
        ),
        migrations.RemoveField(
            model_name='housenamemodel',
            name='read_kwh',
        ),
        migrations.AlterField(
            model_name='housenamemodel',
            name='main_house',
            field=models.BooleanField(help_text='Is the bill belongs this house typed above?'),
        ),
    ]
