# Generated by Django 3.1.7 on 2021-05-14 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0020_auto_20210513_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_FK',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_house_related', to='share.housenamemodel', verbose_name='House Name'),
        ),
        migrations.AlterField(
            model_name='subtenantmodel',
            name='main_tenant_FK',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_house_tenant_related', to='share.housenamemodel', verbose_name='House Name'),
        ),
    ]
