# Generated by Django 3.1.7 on 2021-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0023_auto_20210517_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebillmodel',
            name='days_bill',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='housenamemodel',
            name='main_house',
            field=models.BooleanField(blank=True, help_text='Is the bill belongs this house typed above?', null=True),
        ),
        migrations.AlterField(
            model_name='housenamemodel',
            name='meter',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sub House Name'),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_meter',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subtenantmodel',
            name='sub_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subtenantmodel',
            name='sub_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtenantmodel',
            name='sub_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
