# Generated by Django 3.1.7 on 2021-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0024_auto_20210517_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebillmodel',
            name='days_bill',
            field=models.IntegerField(default=0),
        ),
    ]
