# Generated by Django 3.1.7 on 2021-05-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0025_auto_20210518_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housenamemodel',
            name='main_house',
        ),
        migrations.AlterField(
            model_name='housenamemodel',
            name='meter',
            field=models.IntegerField(default=1),
        ),
    ]
