# Generated by Django 3.1.7 on 2021-05-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0027_auto_20210518_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='last_read_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='read_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
