# Generated by Django 3.1.7 on 2021-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0028_auto_20210518_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housenamemodel',
            name='last_updated_house',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
