# Generated by Django 3.1.7 on 2021-05-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0029_auto_20210528_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebillmodel',
            name='last_updated_bill',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='last_updated_kwh',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_last_updated_house',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subkilowattmodel',
            name='sub_last_updated_kwh',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtenantmodel',
            name='sub_last_updated_tenant',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
