# Generated by Django 3.1.7 on 2021-06-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0030_auto_20210528_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='kwh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='last_read_kwh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='housekilowattmodel',
            name='read_kwh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='housenamemodel',
            name='house_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='House Name'),
        ),
        migrations.AlterField(
            model_name='housetenantmodel',
            name='house_tenant',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Sub House Name'),
        ),
        migrations.AlterField(
            model_name='subkilowattmodel',
            name='sub_kwh',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subkilowattmodel',
            name='sub_last_read_kwh',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subkilowattmodel',
            name='sub_read_kwh',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subtenantmodel',
            name='sub_house_tenant',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
