# Generated by Django 3.1.7 on 2021-06-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0031_auto_20210606_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housenamemodel',
            name='house_name',
            field=models.CharField(blank=True, error_messages={'unique': 'House Name has already been created! Try some diferent one.'}, max_length=150, null=True, unique=True, verbose_name='House Name'),
        ),
        migrations.AlterField(
            model_name='housetenantmodel',
            name='house_tenant',
            field=models.CharField(blank=True, error_messages={'unique': 'Tenant Name has already been created! Try some diferent one.'}, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Sub House Name has already been created! Try some diferent one.'}, max_length=150, null=True, unique=True, verbose_name='Sub House Name'),
        ),
        migrations.AlterField(
            model_name='subtenantmodel',
            name='sub_house_tenant',
            field=models.CharField(blank=True, error_messages={'unique': 'Sub Tenant Name has already been created! Try some diferent one.'}, max_length=150, null=True, unique=True),
        ),
    ]
