# Generated by Django 3.1.7 on 2021-06-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0032_auto_20210607_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housebillmodel',
            name='amount_bill',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='housenamemodel',
            name='house_name',
            field=models.CharField(blank=True, error_messages={'unique': 'House Name has already been created! Try some diferent one.'}, max_length=25, null=True, unique=True, verbose_name='House Name'),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Sub House Name has already been created! Try some diferent one.'}, max_length=25, null=True, unique=True, verbose_name='Sub House Name'),
        ),
    ]
