# Generated by Django 3.1.7 on 2021-06-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0033_auto_20210610_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housenamemodel',
            name='house_name',
            field=models.CharField(blank=True, error_messages={'unique': 'House Name has already been created! Try some diferent one.'}, max_length=100, null=True, unique=True, verbose_name='House Name'),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Sub House Name has already been created! Try some diferent one.'}, max_length=100, null=True, unique=True, verbose_name='Sub House Name'),
        ),
    ]
