# Generated by Django 3.1.7 on 2021-06-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0034_auto_20210611_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetenantmodel',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='housetenantmodel',
            name='house_tenant',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subtenantmodel',
            name='sub_house_tenant',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
