# Generated by Django 3.1.7 on 2021-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0035_auto_20210611_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housenamemodel',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='House Name'),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sub House Name'),
        ),
    ]
