# Generated by Django 3.1.7 on 2021-06-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0037_auto_20210614_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_FK',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_house_related', to='share.housenamemodel', verbose_name='House Name'),
        ),
    ]
