# Generated by Django 3.1.7 on 2021-06-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0039_auto_20210614_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housenamemodel',
            options={'ordering': ['-last_updated_house', 'house_name']},
        ),
        migrations.AlterModelOptions(
            name='subhousenamemodel',
            options={'ordering': ['-sub_last_updated_house', 'sub_house_name']},
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_FK',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_house_related', to='share.housenamemodel', verbose_name='House Name'),
        ),
    ]
