# Generated by Django 3.1.7 on 2021-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0040_auto_20210614_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub House Name'),
        ),
    ]
