# Generated by Django 3.1.7 on 2021-06-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0041_auto_20210614_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housenamemodel',
            options={'ordering': ['-last_updated_house']},
        ),
        migrations.AlterModelOptions(
            name='subhousenamemodel',
            options={'ordering': ['-sub_last_updated_house']},
        ),
        migrations.AddField(
            model_name='subkilowattmodel',
            name='sub_amount_bill',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sub House Name'),
        ),
    ]
