# Generated by Django 3.1.7 on 2021-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0042_auto_20210614_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housenamemodel',
            name='house_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Sub House Name has already been created! Try some diferent one.'}, max_length=100, null=True, unique=True, verbose_name='House Name'),
        ),
        migrations.AlterField(
            model_name='subhousenamemodel',
            name='sub_house_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Sub House Name has already been created! Try some diferent one.'}, max_length=100, null=True, unique=True, verbose_name='Sub House Name'),
        ),
        migrations.AlterField(
            model_name='subkilowattmodel',
            name='sub_amount_bill',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subkilowattmodel',
            name='sub_kwh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subkilowattmodel',
            name='sub_last_read_kwh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subkilowattmodel',
            name='sub_read_kwh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
