# Generated by Django 3.1.7 on 2021-07-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0043_auto_20210620_1516'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='housenamemodel',
            constraint=models.UniqueConstraint(fields=('user_FK', 'house_name'), name='unique_house'),
        ),
    ]
