# Generated by Django 3.1.7 on 2021-07-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0044_auto_20210701_0105'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='housenamemodel',
            name='unique_house',
        ),
        migrations.AlterField(
            model_name='housenamemodel',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='House Name'),
        ),
    ]
